from src.dataclasses import RestrictionEnzyme


RESTRICTION_ENZYMES = (
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.2378245614,
        name="BglI",
        sequence="GCCNNNNNGGC",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.3625614035,
        name="BstXI",
        sequence="CCANNNNNNTGG",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.4132631579,
        name="BglI",
        sequence="GCCNNNNNGGC",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.6120701754,
        name="BglI",
        sequence="GCCNNNNNGGC",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.7095438596,
        name="SfiI",
        sequence="GGCCNNNNNGGCC",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.7836140351,
        name="BglI",
        sequence="GCCNNNNNGGC",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.8195789474,
        name="ORF3A transcription start element",
        sequence="ACTAAAC",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.8195789474,
        name="ClaI",
        sequence="ATCGAT",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.8540350877,
        name="PflMI",
        sequence="CCANNNNNTGG",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.8607719298,
        name="ScaI",
        sequence="AGTACT",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.8779649123,
        name="AvrII",
        sequence="CCTAGG",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.9011850244,
        name="EcoNI",
        sequence="CCTNNNNNAGG",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.9258887683,
        name="StuI",
        sequence="AGGCCT",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.9281345632,
        name="Esp3I",
        sequence="CGTCTCN",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.9318775547,
        name="Eam1101 (AhdI isoschizomer)",
        sequence="GACNNNNNGTC",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.9767934527,
        name="KpnI",
        sequence="GGTACC",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.9820336408,
        name="PacI",
        sequence="TTAATTAA",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.9994385965,
        name="SapI",
        sequence="GCTCTTCN",
    ),
    RestrictionEnzyme(
        location_as_fraction_genome_length=0.9997192982,
        name="NotI",
        sequence="GCGGCCGC",
    ),
)
